name: PR Comment

on:
  pull_request:
    branches: ["*"]

jobs:
  Comments:
    runs-on: ubuntu-latest
    steps:      
      - env:
          PR_NUMBER: ${{ github.event.pull_request.number }} 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export body=$( curl date.jsontest.com/)
          export ip=$(echo $body | jq '.time')
          export co=$( echo $body | jq '.date')
          gh pr comment $PR_NUMBER --body "The time is: $ip Date to day is $co" --repo $GITHUB_REPOSITORY
